-- print("hello")
require("options")
require("keymaps")
require("plugins")
--
require("config.null-ls")
require("config.nvim-cmp")
--
require("user.bufferline")
require("user.colorscheme")
require("user.indentline")
require("user.lsp")
require("user.lualine")
require("user.nvim-tree")
require("user.telescope")
require("user.treesitter")
require("user.tstextobjects")
require("user.ufo")
