-- print("hello")
require("options")
require("keymaps")
require("plugins")
require("user.indentline")
require("user.colorscheme")
--
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.nvim-tree")
require("config.null-ls")
require("user.bufferline")
require("user.ufo")
